export const LOAD_CONFIG = 'LOAD_CONFIG';
export const SET_CONFIG = 'SET_CONFIG';
export const LOAD_DEVICES_FACILITIES = 'LOAD_DEVICES_FACILITIES';
export const LOAD_DEVICES_TASKS = 'LOAD_DEVICES_TASKS';
export const LOAD_TASKS_STATUS = 'LOAD_TASKS_STATUS';
export const LOAD_NETWORK_CONFIG = 'LOAD_NETWORK_CONFIG';
export const LOAD_DEVICE_CONFIG = 'LOAD_DEVICE_CONFIG';

export const configConsts = Object.freeze({
    LOAD_CONFIG ,
    SET_CONFIG,
    LOAD_DEVICES_FACILITIES,
    LOAD_DEVICES_TASKS,
    LOAD_TASKS_STATUS,
    LOAD_NETWORK_CONFIG,
    LOAD_DEVICE_CONFIG
});