export const LOAD_ENCODING_PROFILE_LIST = 'LOAD_ENCODING_PROFILE_LIST';
export const LOAD_ENCODING_PROFILE = 'LOAD_ENCODING_PROFILE';
export const LOAD_STREAM_PROFILE = 'LOAD_STREAM_PROFILE';


export const configConsts = Object.freeze({
    LOAD_ENCODING_PROFILE_LIST ,
    LOAD_ENCODING_PROFILE,
    LOAD_STREAM_PROFILE
});