export const ADD_VIDEO_SOURCE = 'ADD_VIDEO_SOURCE';
export const DELETE_VIDEO_SOURCE = 'DELETE_VIDEO_SOURCE';
export const REPLACE_LAST_VIDEO_SOURCE = 'REPLACE_LAST_VIDEO_SOURCE';
export const LOAD_VIDEO_SOURCES = 'LOAD_VIDEO_SOURCES';
export const STACK_ERROR = 'STACK_ERROR';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';


export const rootConsts = Object.freeze({
	ADD_VIDEO_SOURCE,
	DELETE_VIDEO_SOURCE,
	REPLACE_LAST_VIDEO_SOURCE,
	LOAD_VIDEO_SOURCES,
	STACK_ERROR,
	DISPLAY_ERROR
});